// Generated by server/src/bin/zmk_behaviors.rs. DO NOT EDIT.
// To regenerate, run:
// bazel run //server:zmk_behaviors

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ParameterType {
    Layer,
    Keycode,
    None,
}

#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct ZmkBehavior {
    pub name: &'static str,
    pub label: Option<&'static str>,
    pub display_name: Option<&'static str>,
    pub binding_cells: u32,
    pub include_file: &'static str,
    pub is_default: bool,
    pub parameter_metadata: &'static [ParameterType],
}

pub const ZMK_BEHAVIORS: &[ZmkBehavior] = &[
    ZmkBehavior {
        name: "key_repeat",
        label: Some("key_repeat"),
        display_name: Some("Key Repeat"),
        binding_cells: 0,
        include_file: "key_repeat.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "grave_escape",
        label: Some("gresc"),
        display_name: Some("Grave/Escape"),
        binding_cells: 0,
        include_file: "gresc.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "sysreset",
        label: Some("sys_reset"),
        display_name: Some("Reset"),
        binding_cells: 0,
        include_file: "reset.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "bootload",
        label: Some("bootloader"),
        display_name: Some("Bootloader"),
        binding_cells: 0,
        include_file: "reset.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "none",
        label: Some("none"),
        display_name: Some("None"),
        binding_cells: 0,
        include_file: "none.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "mouse_scroll",
        label: Some("msc"),
        display_name: None,
        binding_cells: 1,
        include_file: "mouse_scroll.dtsi",
        is_default: false,
        parameter_metadata: &[
            ParameterType::None,
        ],
    },
    ZmkBehavior {
        name: "z_so_off",
        label: Some("soft_off"),
        display_name: None,
        binding_cells: 0,
        include_file: "soft_off.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "outputs",
        label: Some("out"),
        display_name: Some("Output Selection"),
        binding_cells: 1,
        include_file: "outputs.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::None,
        ],
    },
    ZmkBehavior {
        name: "mouse_key_press",
        label: Some("mkp"),
        display_name: Some("Mouse Key Press"),
        binding_cells: 1,
        include_file: "mouse_key_press.dtsi",
        is_default: false,
        parameter_metadata: &[
            ParameterType::None,
        ],
    },
    ZmkBehavior {
        name: "mod_tap",
        label: Some("mt"),
        display_name: Some("Mod-Tap"),
        binding_cells: 2,
        include_file: "mod_tap.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::Keycode,
            ParameterType::Keycode,
        ],
    },
    ZmkBehavior {
        name: "momentary_layer",
        label: Some("mo"),
        display_name: Some("Momentary Layer"),
        binding_cells: 1,
        include_file: "momentary_layer.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::Layer,
        ],
    },
    ZmkBehavior {
        name: "to_layer",
        label: Some("to"),
        display_name: Some("To Layer"),
        binding_cells: 1,
        include_file: "to_layer.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::Layer,
        ],
    },
    ZmkBehavior {
        name: "layer_tap",
        label: Some("lt"),
        display_name: Some("Layer-Tap"),
        binding_cells: 2,
        include_file: "layer_tap.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::Layer,
            ParameterType::Keycode,
        ],
    },
    ZmkBehavior {
        name: "bluetooth",
        label: Some("bt"),
        display_name: Some("Bluetooth"),
        binding_cells: 2,
        include_file: "bluetooth.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::None,
            ParameterType::None,
        ],
    },
    ZmkBehavior {
        name: "toggle_layer",
        label: Some("tog"),
        display_name: Some("Toggle Layer"),
        binding_cells: 1,
        include_file: "toggle_layer.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::Layer,
        ],
    },
    ZmkBehavior {
        name: "transparent",
        label: Some("trans"),
        display_name: Some("Transparent"),
        binding_cells: 0,
        include_file: "transparent.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "mouse_move",
        label: Some("mmv"),
        display_name: None,
        binding_cells: 1,
        include_file: "mouse_move.dtsi",
        is_default: false,
        parameter_metadata: &[
            ParameterType::None,
        ],
    },
    ZmkBehavior {
        name: "key_press",
        label: Some("kp"),
        display_name: Some("Key Press"),
        binding_cells: 1,
        include_file: "key_press.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::Keycode,
        ],
    },
    ZmkBehavior {
        name: "bcklight",
        label: Some("bl"),
        display_name: Some("Backlight"),
        binding_cells: 2,
        include_file: "backlight.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::None,
            ParameterType::None,
        ],
    },
    ZmkBehavior {
        name: "studio_unlock",
        label: Some("studio_unlock"),
        display_name: Some("Studio Unlock"),
        binding_cells: 0,
        include_file: "studio_unlock.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "extpower",
        label: Some("ext_power"),
        display_name: Some("External Power"),
        binding_cells: 1,
        include_file: "ext_power.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::None,
        ],
    },
    ZmkBehavior {
        name: "rgb_ug",
        label: Some("rgb_ug"),
        display_name: Some("Underglow"),
        binding_cells: 2,
        include_file: "rgb_underglow.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::None,
            ParameterType::None,
        ],
    },
    ZmkBehavior {
        name: "key_toggle",
        label: Some("kt"),
        display_name: Some("Key Toggle"),
        binding_cells: 1,
        include_file: "key_toggle.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::None,
        ],
    },
    ZmkBehavior {
        name: "macro_tap",
        label: Some("macro_tap"),
        display_name: None,
        binding_cells: 0,
        include_file: "macros.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "macro_press",
        label: Some("macro_press"),
        display_name: None,
        binding_cells: 0,
        include_file: "macros.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "macro_release",
        label: Some("macro_release"),
        display_name: None,
        binding_cells: 0,
        include_file: "macros.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "macro_tap_time",
        label: Some("macro_tap_time"),
        display_name: None,
        binding_cells: 1,
        include_file: "macros.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::None,
        ],
    },
    ZmkBehavior {
        name: "macro_wait_time",
        label: Some("macro_wait_time"),
        display_name: None,
        binding_cells: 1,
        include_file: "macros.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::None,
        ],
    },
    ZmkBehavior {
        name: "macro_pause_for_release",
        label: Some("macro_pause_for_release"),
        display_name: None,
        binding_cells: 0,
        include_file: "macros.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "macro_param_1to1",
        label: Some("macro_param_1to1"),
        display_name: None,
        binding_cells: 0,
        include_file: "macros.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "macro_param_1to2",
        label: Some("macro_param_1to2"),
        display_name: None,
        binding_cells: 0,
        include_file: "macros.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "macro_param_2to1",
        label: Some("macro_param_2to1"),
        display_name: None,
        binding_cells: 0,
        include_file: "macros.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "macro_param_2to2",
        label: Some("macro_param_2to2"),
        display_name: None,
        binding_cells: 0,
        include_file: "macros.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "caps_word",
        label: Some("caps_word"),
        display_name: Some("Caps Word"),
        binding_cells: 0,
        include_file: "caps_word.dtsi",
        is_default: true,
        parameter_metadata: &[
        ],
    },
    ZmkBehavior {
        name: "sticky_key",
        label: Some("sk"),
        display_name: Some("Sticky Key"),
        binding_cells: 1,
        include_file: "sticky_key.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::None,
        ],
    },
    ZmkBehavior {
        name: "sticky_layer",
        label: Some("sl"),
        display_name: Some("Sticky Layer"),
        binding_cells: 1,
        include_file: "sticky_key.dtsi",
        is_default: true,
        parameter_metadata: &[
            ParameterType::None,
        ],
    },
];
