load("@rules_rust_prost//:defs.bzl", "rust_prost_library")

rust_prost_library(
    name = "zmk_studio_rust_proto",
    proto = "@zmk_studio_messages//:zmk_studio_proto",
    visibility = ["//visibility:public"],
)
